version: '3.8'

services:
  microblog-api:
    build: .
    container_name: uala-microblog-api
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microblog-network

networks:
  microblog-network:
    driver: bridge
